### ISSUE TITLE
Build the Coder login UX flow

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder-desktop-macos#3]
On starting Coder Desktop, we prompt the user to log into their Coder deployment.

We should use the native UI kit for this initial version.

![Image](https://github.com/user-attachments/assets/d85838a1-b10c-4888-a752-aad23529c9b9)

We should attempt to read the Coder URL from the CLI config directory, if present, and autofill the URL box.  We should still prompt for confirmation.

![Image](https://github.com/user-attachments/assets/71d17104-3f10-4075-b143-fbbdfd95ea47)

This is based on the usual Coder login.  Alternatively, we could bounce the user to the default browser to log in on the web, and pass the API key back to the Coder Desktop app via a socket on localhost.

**Comment by ethanndickson** [comment]
Yeah, for this beta version I think we should just open the browser and get the user to paste a token from `/cli-auth`.
